import { getScopedStorageKey, getAuthHeaders } from "./auth.js";

const BASE_KEY = "employees";
function getStorageKey() {
  return getScopedStorageKey(BASE_KEY);
}

export const INITIAL_DEFAULT_EMPLOYEES = [
  // ==========================================
  // 1. MATCHA TEA (MA330) — 15 EMPLOYEES
  // ==========================================
  // HOUSEKEEPING (5 EMPLOYEES)
  {
    id: "HK-101",
    staff_id: "HK-101",
    staffId: "HK-101",
    name: "Sunita Devi",
    username: "sunita.devi",
    password: "matcha123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "1st & 2nd Floor Rooms",
    assignedArea: "1st & 2nd Floor Rooms",
    assigned_work: "1st & 2nd Floor Room Turnover & Sanitization (Rooms 101, 102)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sunita.hk@hotel.com",
    phone: "+91 98765 43213",
    salary: 26000,
    joinedDate: "2025-02-10",
    joining_date: "2025-02-10",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-102",
    staff_id: "HK-102",
    staffId: "HK-102",
    name: "Ramesh Kumar",
    username: "ramesh.kumar",
    password: "matcha123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "3rd & 4th Floor Rooms",
    assignedArea: "3rd & 4th Floor Rooms",
    assigned_work: "3rd & 4th Floor Deep Clean & Inspection (Rooms 104, 105)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ramesh.hk@hotel.com",
    phone: "+91 98765 43214",
    salary: 24000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-103",
    staff_id: "HK-103",
    staffId: "HK-103",
    name: "Anita Sharma",
    username: "anita.sharma",
    password: "matcha123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "Suites & VIP Rooms",
    assignedArea: "Suites & VIP Rooms",
    assigned_work: "VIP Suites & Executive Floor Refresh (Room 1001)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "anita.hk@hotel.com",
    phone: "+91 98765 43215",
    salary: 25000,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-104",
    staff_id: "HK-104",
    staffId: "HK-104",
    name: "Kavita Rao",
    username: "kavita.rao",
    password: "matcha123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (03:00 PM - 11:30 PM)",
    assigned_area: "5th to 8th Floor Rooms",
    assignedArea: "5th to 8th Floor Rooms",
    assigned_work: "Evening Turndown & Linen Refresh (Rooms 107, 108)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "kavita.hk@hotel.com",
    phone: "+91 98765 43216",
    salary: 23500,
    joinedDate: "2025-04-12",
    joining_date: "2025-04-12",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-105",
    staff_id: "HK-105",
    staffId: "HK-105",
    name: "Vikas Joshi",
    username: "vikas.joshi",
    password: "matcha123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Night (11:00 PM - 07:30 AM)",
    assigned_area: "Public Areas & Deep Clean",
    assignedArea: "Public Areas & Deep Clean",
    assigned_work: "Lobby, Lounge & Public Restrooms Sanitization",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "vikas.hk@hotel.com",
    phone: "+91 98765 43217",
    salary: 24500,
    joinedDate: "2025-05-18",
    joining_date: "2025-05-18",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },

  // KITCHEN (5 EMPLOYEES)
  {
    id: "KIT-101",
    staff_id: "KIT-101",
    staffId: "KIT-101",
    name: "Sanjeev Kapoor",
    username: "sanjeev.kapoor",
    password: "matcha123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Main Kitchen & Fine Dining",
    assignedArea: "Main Kitchen & Fine Dining",
    assigned_work: "Head Chef: Menu Planning & Breakfast/Dinner Buffet",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sanjeev.chef@hotel.com",
    phone: "+91 98765 44001",
    salary: 65000,
    joinedDate: "2025-01-10",
    joining_date: "2025-01-10",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-102",
    staff_id: "KIT-102",
    staffId: "KIT-102",
    name: "Rahul Rawat",
    username: "rahul.rawat",
    password: "matcha123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Hot Kitchen & Grills",
    assignedArea: "Hot Kitchen & Grills",
    assigned_work: "Sous Chef: Hot Kitchen, Tandoor & Room Service KOTs",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rahul.cook@hotel.com",
    phone: "+91 98765 44002",
    salary: 42000,
    joinedDate: "2025-02-15",
    joining_date: "2025-02-15",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-103",
    staff_id: "KIT-103",
    staffId: "KIT-103",
    name: "Manjeet Kaur",
    username: "manjeet.kaur",
    password: "matcha123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (06:00 - 14:30)",
    assigned_area: "Bakery & Cold Pantry",
    assignedArea: "Bakery & Cold Pantry",
    assigned_work: "Pastry & Cold Pantry: Fresh Bakes, Desserts & Salads",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "manjeet.bakery@hotel.com",
    phone: "+91 98765 44003",
    salary: 38000,
    joinedDate: "2025-03-20",
    joining_date: "2025-03-20",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-104",
    staff_id: "KIT-104",
    staffId: "KIT-104",
    name: "Vikram Malhotra",
    username: "vikram.malhotra",
    password: "matcha123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Live Counter & Banquet",
    assignedArea: "Live Counter & Banquet",
    assigned_work: "Line Cook & Grill Specialist: Live Counter & Fast Orders",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "vikram.chef@hotel.com",
    phone: "+91 98765 44004",
    salary: 36000,
    joinedDate: "2025-04-01",
    joining_date: "2025-04-01",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-105",
    staff_id: "KIT-105",
    staffId: "KIT-105",
    name: "Deepak Negi",
    username: "deepak.negi",
    password: "matcha123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Buffet Prep & Cold Pantry",
    assignedArea: "Buffet Prep & Cold Pantry",
    assigned_work: "Breakfast Buffet Station, Pantry Prep & Ingredient Quality Check",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "deepak.chef@hotel.com",
    phone: "+91 98765 44005",
    salary: 33000,
    joinedDate: "2025-04-15",
    joining_date: "2025-04-15",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },

  // ACCOUNTING (5 EMPLOYEES)
  {
    id: "ACC-101",
    staff_id: "ACC-101",
    staffId: "ACC-101",
    name: "Priya Sharma",
    username: "priya.sharma",
    password: "matcha123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Finance & Audit Desk",
    assignedArea: "Finance & Audit Desk",
    assigned_work: "Daily Ledger Balancing, GST Tax Audits & Cash Reports",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "accountant@hotel.com",
    phone: "+91 98765 43212",
    salary: 52000,
    joinedDate: "2025-02-01",
    joining_date: "2025-02-01",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-102",
    staff_id: "ACC-102",
    staffId: "ACC-102",
    name: "Amit Patel",
    username: "amit.patel",
    password: "matcha123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Invoicing & Billing Desk",
    assignedArea: "Invoicing & Billing Desk",
    assigned_work: "Guest Folio Invoicing & POS Cash Register Management",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "amit.billing@hotel.com",
    phone: "+91 98765 45002",
    salary: 40000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-103",
    staff_id: "ACC-103",
    staffId: "ACC-103",
    name: "Divya Mehra",
    username: "divya.mehra",
    password: "matcha123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Audit & Payroll Desk",
    assignedArea: "Audit & Payroll Desk",
    assigned_work: "Monthly Payroll Reconciliation & Supplier Ledger Audits",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "divya.acc@hotel.com",
    phone: "+91 98765 45003",
    salary: 46000,
    joinedDate: "2025-03-10",
    joining_date: "2025-03-10",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-104",
    staff_id: "ACC-104",
    staffId: "ACC-104",
    name: "Rajesh Singhania",
    username: "rajesh.singhania",
    password: "matcha123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Tax & Compliance Office",
    assignedArea: "Tax & Compliance Office",
    assigned_work: "TDS Filings, Corporate Tax Reconciliation & Quarterly Reviews",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rajesh.acc@hotel.com",
    phone: "+91 98765 45004",
    salary: 48000,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-105",
    staff_id: "ACC-105",
    staffId: "ACC-105",
    name: "Neha Bansal",
    username: "neha.bansal",
    password: "matcha123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Front Desk Cash Counter",
    assignedArea: "Front Desk Cash Counter",
    assigned_work: "Daily Shift Float Reconciliation & Credit Card Settlement",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "neha.acc@hotel.com",
    phone: "+91 98765 45005",
    salary: 37000,
    joinedDate: "2025-04-01",
    joining_date: "2025-04-01",
    status: "Active",
    orgId: "MA330",
    org_id: "MA330",
    org: "Matcha Tea",
    org_name: "Matcha Tea",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
  },
];

export const ASHIRWAD_EMPLOYEES = [
  // ==========================================
  // 2. ASHIRWAD (AS435) — 15 EMPLOYEES
  // ==========================================
  // HOUSEKEEPING (5 EMPLOYEES)
  {
    id: "HK-ASH-101",
    staff_id: "HK-ASH-101",
    staffId: "HK-ASH-101",
    name: "Kavita Shinde",
    username: "kavita.shinde",
    password: "ashirwad123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "1st & 2nd Floor Wing",
    assignedArea: "1st & 2nd Floor Wing",
    assigned_work: "1st & 2nd Floor Rooms Turnover & Linen Clean (Rooms 101-105)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "kavita.s@ashirwad.com",
    phone: "+91 98000 44001",
    salary: 28000,
    joinedDate: "2025-01-15",
    joining_date: "2025-01-15",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-ASH-102",
    staff_id: "HK-ASH-102",
    staffId: "HK-ASH-102",
    name: "Vikas Joshi",
    username: "vikas.joshi",
    password: "ashirwad123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (15:00 - 23:00)",
    assigned_area: "3rd & 4th Floor Wing",
    assignedArea: "3rd & 4th Floor Wing",
    assigned_work: "3rd & 4th Floor Stayover Clean & Restock (Rooms 106-110)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "vikas.j@ashirwad.com",
    phone: "+91 98000 44002",
    salary: 26000,
    joinedDate: "2025-02-01",
    joining_date: "2025-02-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-ASH-103",
    staff_id: "HK-ASH-103",
    staffId: "HK-ASH-103",
    name: "Suresh Kumar",
    username: "suresh.kumar",
    password: "ashirwad123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 - 15:00)",
    assigned_area: "Lobby, Lawns & Banquet Halls",
    assignedArea: "Lobby, Lawns & Banquet Halls",
    assigned_work: "Public Area Sanitization, Lobby, Restrooms & Lawn Maintenance",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "suresh.k@ashirwad.com",
    phone: "+91 98000 44003",
    salary: 25000,
    joinedDate: "2025-02-15",
    joining_date: "2025-02-15",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-ASH-104",
    staff_id: "HK-ASH-104",
    staffId: "HK-ASH-104",
    name: "Radhika Nair",
    username: "radhika.nair",
    password: "ashirwad123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 - 15:00)",
    assigned_area: "Royal Villas & Suites",
    assignedArea: "Royal Villas & Suites",
    assigned_work: "Luxury Villa Deep Clean, Turndown & VIP Guest Amenities",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "radhika.n@ashirwad.com",
    phone: "+91 98000 44004",
    salary: 27500,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-ASH-105",
    staff_id: "HK-ASH-105",
    staffId: "HK-ASH-105",
    name: "Manoj Yadav",
    username: "manoj.yadav",
    password: "ashirwad123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Night (23:00 - 07:00)",
    assigned_area: "Night Facility & Linen Laundry",
    assignedArea: "Night Facility & Linen Laundry",
    assigned_work: "Night Sanitization, Emergency Turnovers & Laundry Facility",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "manoj.y@ashirwad.com",
    phone: "+91 98000 44005",
    salary: 25500,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },

  // KITCHEN (5 EMPLOYEES)
  {
    id: "KIT-ASH-101",
    staff_id: "KIT-ASH-101",
    staffId: "KIT-ASH-101",
    name: "Ranveer Brar",
    username: "ranveer.brar",
    password: "ashirwad123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Main Kitchen & Fine Dining",
    assignedArea: "Main Kitchen & Fine Dining",
    assigned_work: "Executive Chef: Royal Rajasthani & Continental Cuisine, Menu Planning",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ranveer.b@ashirwad.com",
    phone: "+91 98000 55001",
    salary: 68000,
    joinedDate: "2025-01-10",
    joining_date: "2025-01-10",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-ASH-102",
    staff_id: "KIT-ASH-102",
    staffId: "KIT-ASH-102",
    name: "Ajay Chopra",
    username: "ajay.chopra",
    password: "ashirwad123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Tandoor & Live Grill Station",
    assignedArea: "Tandoor & Live Grill Station",
    assigned_work: "Sous Chef: Live Grill, Tandoor & Evening Dining Service",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ajay.c@ashirwad.com",
    phone: "+91 98000 55002",
    salary: 45000,
    joinedDate: "2025-02-15",
    joining_date: "2025-02-15",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-ASH-103",
    staff_id: "KIT-ASH-103",
    staffId: "KIT-ASH-103",
    name: "Meenakshi Sharma",
    username: "meenakshi.sharma",
    password: "ashirwad123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (06:00 - 14:30)",
    assigned_area: "Pastry & Bakery Kitchen",
    assignedArea: "Pastry & Bakery Kitchen",
    assigned_work: "Pastry Chef: Breakfast Buffet & Artisanal Bakery Items",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "meenakshi.s@ashirwad.com",
    phone: "+91 98000 55003",
    salary: 38000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-ASH-104",
    staff_id: "KIT-ASH-104",
    staffId: "KIT-ASH-104",
    name: "Vikram Malhotra",
    username: "vikram.malhotra",
    password: "ashirwad123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Hot Kitchen & Banquet Line",
    assignedArea: "Hot Kitchen & Banquet Line",
    assigned_work: "Line Cook: Fast Order Processing, Sauce Station & Banquet Prep",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "vikram.m@ashirwad.com",
    phone: "+91 98000 55004",
    salary: 36000,
    joinedDate: "2025-03-20",
    joining_date: "2025-03-20",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-ASH-105",
    staff_id: "KIT-ASH-105",
    staffId: "KIT-ASH-105",
    name: "Sunil Verma",
    username: "sunil.verma",
    password: "ashirwad123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Cold Kitchen & Salad Bar",
    assignedArea: "Cold Kitchen & Salad Bar",
    assigned_work: "Salad Prep, Fresh Juices, Cold Pantry & HACCP Food Hygiene",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sunil.v@ashirwad.com",
    phone: "+91 98000 55005",
    salary: 32000,
    joinedDate: "2025-04-01",
    joining_date: "2025-04-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },

  // ACCOUNTING (5 EMPLOYEES)
  {
    id: "ACC-ASH-101",
    staff_id: "ACC-ASH-101",
    staffId: "ACC-ASH-101",
    name: "Sanjay Rao",
    username: "sanjay.rao",
    password: "ashirwad123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Finance & Audit Office",
    assignedArea: "Finance & Audit Office",
    assigned_work: "Chief Accountant: Balance Sheets, GST Returns & Financial Audits",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sanjay.r@ashirwad.com",
    phone: "+91 98000 66001",
    salary: 55000,
    joinedDate: "2025-01-15",
    joining_date: "2025-01-15",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-ASH-102",
    staff_id: "ACC-ASH-102",
    staffId: "ACC-ASH-102",
    name: "Pooja Agarwal",
    username: "pooja.agarwal",
    password: "ashirwad123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Billing & Collections Desk",
    assignedArea: "Billing & Collections Desk",
    assigned_work: "Guest Billing, Folio Invoicing & Night Audit Verification",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "pooja.a@ashirwad.com",
    phone: "+91 98000 66002",
    salary: 42000,
    joinedDate: "2025-02-01",
    joining_date: "2025-02-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-ASH-103",
    staff_id: "ACC-ASH-103",
    staffId: "ACC-ASH-103",
    name: "Amit Patel",
    username: "amit.patel",
    password: "ashirwad123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Accounts Payable Office",
    assignedArea: "Accounts Payable Office",
    assigned_work: "Vendor Invoices, Purchase Orders & Supplier Payments Reconciliation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "amit.p@ashirwad.com",
    phone: "+91 98000 66003",
    salary: 40000,
    joinedDate: "2025-02-20",
    joining_date: "2025-02-20",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-ASH-104",
    staff_id: "ACC-ASH-104",
    staffId: "ACC-ASH-104",
    name: "Divya Mehra",
    username: "divya.mehra",
    password: "ashirwad123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Payroll & Compliance Desk",
    assignedArea: "Payroll & Compliance Desk",
    assigned_work: "Monthly Staff Payroll, PF / ESI Compliance & Employee Advances",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "divya.m@ashirwad.com",
    phone: "+91 98000 66004",
    salary: 46000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-ASH-105",
    staff_id: "ACC-ASH-105",
    staffId: "ACC-ASH-105",
    name: "Rohit Singh",
    username: "rohit.singh",
    password: "ashirwad123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Cash Counter & Vault",
    assignedArea: "Cash Counter & Vault",
    assigned_work: "Daily Cash Inflow Tracking, Bank Deposits & POS Terminal Balancing",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rohit.s@ashirwad.com",
    phone: "+91 98000 66005",
    salary: 39000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "AS435",
    org_id: "AS435",
    org: "Ashirwad",
    org_name: "Ashirwad",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
];

export const CHEERY_EMPLOYEES = [
  // ==========================================
  // 3. CHEERY CLOTHING (CH560) — 15 EMPLOYEES
  // ==========================================
  // HOUSEKEEPING (5 EMPLOYEES)
  {
    id: "HK-CH-201",
    staff_id: "HK-CH-201",
    staffId: "HK-CH-201",
    name: "Rhea Kapoor",
    username: "rhea.kapoor",
    password: "cheery123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 - 15:00)",
    assigned_area: "Dressing Vanity Suites",
    assignedArea: "Dressing Vanity Suites",
    assigned_work: "Wardrobe & VIP Suite Turnovers",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rhea.k@cheeryclothing.com",
    phone: "+91 98111 20002",
    salary: 30000,
    joinedDate: "2025-02-05",
    joining_date: "2025-02-05",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-CH-202",
    staff_id: "HK-CH-202",
    staffId: "HK-CH-202",
    name: "Tina Dsouza",
    username: "tina.dsouza",
    password: "cheery123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (15:00 - 23:00)",
    assigned_area: "Runway Lounge & Suites",
    assignedArea: "Runway Lounge & Suites",
    assigned_work: "Public Area Sanitization & Evening Turnovers",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "tina.d@cheeryclothing.com",
    phone: "+91 98111 20013",
    salary: 27000,
    joinedDate: "2025-03-20",
    joining_date: "2025-03-20",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-CH-203",
    staff_id: "HK-CH-203",
    staffId: "HK-CH-203",
    name: "Aakash Bose",
    username: "aakash.bose",
    password: "cheery123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 - 15:00)",
    assigned_area: "Lobby & Designer Suites",
    assignedArea: "Lobby & Designer Suites",
    assigned_work: "Designer Suite Refresh & Public Restroom Disinfection",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "aakash.b@cheeryclothing.com",
    phone: "+91 98111 20014",
    salary: 26500,
    joinedDate: "2025-04-01",
    joining_date: "2025-04-01",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-CH-204",
    staff_id: "HK-CH-204",
    staffId: "HK-CH-204",
    name: "Preeti Sen",
    username: "preeti.sen",
    password: "cheery123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (15:00 - 23:00)",
    assigned_area: "Boutique Fitting Suites",
    assignedArea: "Boutique Fitting Suites",
    assigned_work: "Linen Exchange, Evening Restock & Fitting Suite Prep",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "preeti.s@cheeryclothing.com",
    phone: "+91 98111 20015",
    salary: 26000,
    joinedDate: "2025-04-15",
    joining_date: "2025-04-15",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-CH-205",
    staff_id: "HK-CH-205",
    staffId: "HK-CH-205",
    name: "Mohan Lal",
    username: "mohan.lal",
    password: "cheery123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Night (23:00 - 07:00)",
    assigned_area: "Night Facility & Stock Rooms",
    assignedArea: "Night Facility & Stock Rooms",
    assigned_work: "Night Deep Clean, Stock Room Sanitization & Garbage Dispatch",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "mohan.l@cheeryclothing.com",
    phone: "+91 98111 20016",
    salary: 25500,
    joinedDate: "2025-05-01",
    joining_date: "2025-05-01",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },

  // KITCHEN (5 EMPLOYEES)
  {
    id: "KIT-CH-201",
    staff_id: "KIT-CH-201",
    staffId: "KIT-CH-201",
    name: "Manish Malhotra",
    username: "manish.malhotra",
    password: "cheery123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Runway Cafe & Bar",
    assignedArea: "Runway Cafe & Bar",
    assigned_work: "Executive Chef: Gourmet Fusion Cuisine & Special Tastings",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "manish.m@cheeryclothing.com",
    phone: "+91 98111 20003",
    salary: 55000,
    joinedDate: "2025-02-10",
    joining_date: "2025-02-10",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-CH-202",
    staff_id: "KIT-CH-202",
    staffId: "KIT-CH-202",
    name: "Karan Khurana",
    username: "karan.khurana",
    password: "cheery123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Boutique Bistro",
    assignedArea: "Boutique Bistro",
    assigned_work: "Sous Chef: Evening Bistro & Beverages Prep",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "karan.k@cheeryclothing.com",
    phone: "+91 98111 20012",
    salary: 40000,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-CH-203",
    staff_id: "KIT-CH-203",
    staffId: "KIT-CH-203",
    name: "Tara Dsouza",
    username: "tara.dsouza",
    password: "cheery123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (06:00 - 14:30)",
    assigned_area: "Bakery & Artisan Desserts",
    assignedArea: "Bakery & Artisan Desserts",
    assigned_work: "Artisanal Pastries, Croissants & Coffee Service",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "tara.d@cheeryclothing.com",
    phone: "+91 98111 20017",
    salary: 37000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-CH-204",
    staff_id: "KIT-CH-204",
    staffId: "KIT-CH-204",
    name: "Varun Bajaj",
    username: "varun.bajaj",
    password: "cheery123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Grill & Live Bar Counter",
    assignedArea: "Grill & Live Bar Counter",
    assigned_work: "Live Bar Snacks, Finger Foods & Tapas Preparation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "varun.b@cheeryclothing.com",
    phone: "+91 98111 20018",
    salary: 35000,
    joinedDate: "2025-04-10",
    joining_date: "2025-04-10",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-CH-205",
    staff_id: "KIT-CH-205",
    staffId: "KIT-CH-205",
    name: "Simran Arora",
    username: "simran.arora",
    password: "cheery123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Cold Pantry & Salads",
    assignedArea: "Cold Pantry & Salads",
    assigned_work: "Gourmet Salads, Fresh Juices & Kitchen HACCP Sanitation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "simran.a@cheeryclothing.com",
    phone: "+91 98111 20019",
    salary: 32000,
    joinedDate: "2025-04-20",
    joining_date: "2025-04-20",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },

  // ACCOUNTING (5 EMPLOYEES)
  {
    id: "ACC-CH-201",
    staff_id: "ACC-CH-201",
    staffId: "ACC-CH-201",
    name: "Rakesh Jhunjhunwala",
    username: "rakesh.j",
    password: "cheery123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Finance Office",
    assignedArea: "Finance Office",
    assigned_work: "Finance Controller: Balance Sheets & Strategic Budgets",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rakesh.j@cheeryclothing.com",
    phone: "+91 98111 20010",
    salary: 60000,
    joinedDate: "2025-01-15",
    joining_date: "2025-01-15",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-CH-202",
    staff_id: "ACC-CH-202",
    staffId: "ACC-CH-202",
    name: "Simran Kaur",
    username: "simran.kaur",
    password: "cheery123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Billing Counter",
    assignedArea: "Billing Counter",
    assigned_work: "POS Store Invoicing & GST Returns Reconciliation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "simran.k@cheeryclothing.com",
    phone: "+91 98111 20011",
    salary: 40000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-CH-203",
    staff_id: "ACC-CH-203",
    staffId: "ACC-CH-203",
    name: "Hardik Mehta",
    username: "hardik.mehta",
    password: "cheery123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Accounts Payable Office",
    assignedArea: "Accounts Payable Office",
    assigned_work: "Vendor Bills, Purchase Orders & Supplier Reconciliation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "hardik.m@cheeryclothing.com",
    phone: "+91 98111 20020",
    salary: 42000,
    joinedDate: "2025-03-20",
    joining_date: "2025-03-20",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-CH-204",
    staff_id: "ACC-CH-204",
    staffId: "ACC-CH-204",
    name: "Ananya Roy",
    username: "ananya.roy",
    password: "cheery123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Payroll Desk",
    assignedArea: "Payroll Desk",
    assigned_work: "Staff Payroll, ESI/PF Deductions & Monthly Audit",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ananya.r@cheeryclothing.com",
    phone: "+91 98111 20021",
    salary: 45000,
    joinedDate: "2025-04-01",
    joining_date: "2025-04-01",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-CH-205",
    staff_id: "ACC-CH-205",
    staffId: "ACC-CH-205",
    name: "Kunal Shah",
    username: "kunal.shah",
    password: "cheery123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Cash Counter & Banking",
    assignedArea: "Cash Counter & Banking",
    assigned_work: "Daily Retail Cash Balance & Bank Credit Verification",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "kunal.s@cheeryclothing.com",
    phone: "+91 98111 20022",
    salary: 38000,
    joinedDate: "2025-04-15",
    joining_date: "2025-04-15",
    status: "Active",
    orgId: "CH560",
    org_id: "CH560",
    org: "Cheery Clothing",
    org_name: "Cheery Clothing",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
];

export const JAIPUR_EMPLOYEES = [
  // ==========================================
  // 4. JAIPUR BRANCH (JP01) — 15 EMPLOYEES
  // ==========================================
  // HOUSEKEEPING (5 EMPLOYEES)
  {
    id: "HK-JP-101",
    staff_id: "HK-JP-101",
    staffId: "HK-JP-101",
    name: "Priya Meena",
    username: "priya.meena",
    password: "jaipur123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "Royal Heritage Wing",
    assignedArea: "Royal Heritage Wing",
    assigned_work: "1st & 2nd Floor Room Turnover & Sanitization (Rooms 101, 102)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "priya.jp@hotel.com",
    phone: "+91 98290 11001",
    salary: 26000,
    joinedDate: "2025-02-10",
    joining_date: "2025-02-10",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-JP-102",
    staff_id: "HK-JP-102",
    staffId: "HK-JP-102",
    name: "Suresh Gurjar",
    username: "suresh.gurjar",
    password: "jaipur123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "Haveli Suites & Rooms",
    assignedArea: "Haveli Suites & Rooms",
    assigned_work: "3rd & 4th Floor Deep Clean & Inspection (Rooms 104, 105)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "suresh.jp@hotel.com",
    phone: "+91 98290 11002",
    salary: 25000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-JP-103",
    staff_id: "HK-JP-103",
    staffId: "HK-JP-103",
    name: "Meera Rathore",
    username: "meera.rathore",
    password: "jaipur123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (03:00 PM - 11:30 PM)",
    assigned_area: "Palace Floor & Courtyard",
    assignedArea: "Palace Floor & Courtyard",
    assigned_work: "VIP Palace Suites & Evening Turndown (Room 201)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "meera.jp@hotel.com",
    phone: "+91 98290 11003",
    salary: 24500,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-JP-104",
    staff_id: "HK-JP-104",
    staffId: "HK-JP-104",
    name: "Govind Sharma",
    username: "govind.sharma",
    password: "jaipur123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (03:00 PM - 11:30 PM)",
    assigned_area: "2nd & 3rd Floor Rooms",
    assignedArea: "2nd & 3rd Floor Rooms",
    assigned_work: "Evening Room Service & Linen Refresh (Rooms 202, 203)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "govind.jp@hotel.com",
    phone: "+91 98290 11004",
    salary: 24000,
    joinedDate: "2025-04-10",
    joining_date: "2025-04-10",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-JP-105",
    staff_id: "HK-JP-105",
    staffId: "HK-JP-105",
    name: "Rekha Kanwar",
    username: "rekha.kanwar",
    password: "jaipur123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Night (11:00 PM - 07:30 AM)",
    assigned_area: "Lobby & Heritage Gardens",
    assignedArea: "Lobby & Heritage Gardens",
    assigned_work: "Heritage Lobby, Courtyard & Night Disinfection",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rekha.jp@hotel.com",
    phone: "+91 98290 11005",
    salary: 25500,
    joinedDate: "2025-05-01",
    joining_date: "2025-05-01",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },

  // KITCHEN (5 EMPLOYEES)
  {
    id: "KIT-JP-101",
    staff_id: "KIT-JP-101",
    staffId: "KIT-JP-101",
    name: "Mahendra Singh",
    username: "mahendra.singh",
    password: "jaipur123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Royal Dining Kitchen",
    assignedArea: "Royal Dining Kitchen",
    assigned_work: "Head Chef: Royal Rajasthani Thali, Dal Baati Churma & Breakfast Buffet",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "mahendra.chef@jaipur.com",
    phone: "+91 98290 22001",
    salary: 65000,
    joinedDate: "2025-01-15",
    joining_date: "2025-01-15",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-JP-102",
    staff_id: "KIT-JP-102",
    staffId: "KIT-JP-102",
    name: "Bhanwar Lal",
    username: "bhanwar.lal",
    password: "jaipur123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Tandoor & Kebab Station",
    assignedArea: "Tandoor & Kebab Station",
    assigned_work: "Sous Chef: Tandoor Breads, Laal Maas & Grills",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "bhanwar.cook@jaipur.com",
    phone: "+91 98290 22002",
    salary: 44000,
    joinedDate: "2025-02-20",
    joining_date: "2025-02-20",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-JP-103",
    staff_id: "KIT-JP-103",
    staffId: "KIT-JP-103",
    name: "Geeta Soni",
    username: "geeta.soni",
    password: "jaipur123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (06:00 - 14:30)",
    assigned_area: "Halwai & Sweets Counter",
    assignedArea: "Halwai & Sweets Counter",
    assigned_work: "Pastry & Sweets: Fresh Ghevar, Mawa Kachori & Desserts",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "geeta.halwai@jaipur.com",
    phone: "+91 98290 22003",
    salary: 38000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-JP-104",
    staff_id: "KIT-JP-104",
    staffId: "KIT-JP-104",
    name: "Ratan Kumawat",
    username: "ratan.kumawat",
    password: "jaipur123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Courtyard Live Counter",
    assignedArea: "Courtyard Live Counter",
    assigned_work: "Live Counter Chef: Snacks, Chaat & Quick Bites",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ratan.cook@jaipur.com",
    phone: "+91 98290 22004",
    salary: 35000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-JP-105",
    staff_id: "KIT-JP-105",
    staffId: "KIT-JP-105",
    name: "Dinesh Prajapat",
    username: "dinesh.prajapat",
    password: "jaipur123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Cold Pantry & Grocery Store",
    assignedArea: "Cold Pantry & Grocery Store",
    assigned_work: "Pantry Prep, Veg/Fruit Washing & Inventory Checks",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "dinesh.kitchen@jaipur.com",
    phone: "+91 98290 22005",
    salary: 32000,
    joinedDate: "2025-04-15",
    joining_date: "2025-04-15",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },

  // ACCOUNTING (5 EMPLOYEES)
  {
    id: "ACC-JP-101",
    staff_id: "ACC-JP-101",
    staffId: "ACC-JP-101",
    name: "Rakesh Agarwal",
    username: "rakesh.agarwal",
    password: "jaipur123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Finance & Accounts Office",
    assignedArea: "Finance & Accounts Office",
    assigned_work: "Senior Accounts Controller: Daily Ledger Balancing & Financial Audits",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "rakesh.acc@jaipur.com",
    phone: "+91 98290 33001",
    salary: 55000,
    joinedDate: "2025-01-20",
    joining_date: "2025-01-20",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-JP-102",
    staff_id: "ACC-JP-102",
    staffId: "ACC-JP-102",
    name: "Sunita Khandelwal",
    username: "sunita.khandelwal",
    password: "jaipur123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Guest Billing & POS Desk",
    assignedArea: "Guest Billing & POS Desk",
    assigned_work: "Front Office Billing, Guest Checkout Folios & GST Invoices",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sunita.bill@jaipur.com",
    phone: "+91 98290 33002",
    salary: 42000,
    joinedDate: "2025-02-15",
    joining_date: "2025-02-15",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-JP-103",
    staff_id: "ACC-JP-103",
    staffId: "ACC-JP-103",
    name: "Mohit Singhal",
    username: "mohit.singhal",
    password: "jaipur123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Vendor & Expense Cell",
    assignedArea: "Vendor & Expense Cell",
    assigned_work: "Vendor Invoices, Purchase Orders & Expense Ledger Reconciliation",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "mohit.acc@jaipur.com",
    phone: "+91 98290 33003",
    salary: 44000,
    joinedDate: "2025-03-10",
    joining_date: "2025-03-10",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-JP-104",
    staff_id: "ACC-JP-104",
    staffId: "ACC-JP-104",
    name: "Pooja Maheshwari",
    username: "pooja.maheshwari",
    password: "jaipur123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Cash Vault & Settlement",
    assignedArea: "Cash Vault & Settlement",
    assigned_work: "Daily Cash Counter Reconciliation & Bank Deposit Verification",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "pooja.cash@jaipur.com",
    phone: "+91 98290 33004",
    salary: 40000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-JP-105",
    staff_id: "ACC-JP-105",
    staffId: "ACC-JP-105",
    name: "Ashok Goyal",
    username: "ashok.goyal",
    password: "jaipur123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Tax & Compliance Office",
    assignedArea: "Tax & Compliance Office",
    assigned_work: "GST Returns, TDS Compliance & Monthly Balance Sheet Filing",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "ashok.tax@jaipur.com",
    phone: "+91 98290 33005",
    salary: 48000,
    joinedDate: "2025-04-05",
    joining_date: "2025-04-05",
    status: "Active",
    orgId: "JP01",
    org_id: "JP01",
    org: "Jaipur Branch",
    org_name: "Jaipur Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

export const AJMER_EMPLOYEES = [
  // ==========================================
  // 5. AJMER BRANCH (AJ01) — 15 EMPLOYEES
  // ==========================================
  // HOUSEKEEPING (5 EMPLOYEES)
  {
    id: "HK-AJ-101",
    staff_id: "HK-AJ-101",
    staffId: "HK-AJ-101",
    name: "Sunita Rawat",
    username: "sunita.rawat",
    password: "ajmer123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "Lake View Deluxe Wing",
    assignedArea: "Lake View Deluxe Wing",
    assigned_work: "1st & 2nd Floor Room Turnover & Sanitization (Rooms 101, 102)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "sunita.aj@hotel.com",
    phone: "+91 98280 11001",
    salary: 26000,
    joinedDate: "2025-02-10",
    joining_date: "2025-02-10",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-AJ-102",
    staff_id: "HK-AJ-102",
    staffId: "HK-AJ-102",
    name: "Mukesh Bairwa",
    username: "mukesh.bairwa",
    password: "ajmer123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Morning (07:00 AM - 03:30 PM)",
    assigned_area: "Dargah View Suites",
    assignedArea: "Dargah View Suites",
    assigned_work: "3rd & 4th Floor Deep Clean & Inspection (Rooms 104, 105)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "mukesh.aj@hotel.com",
    phone: "+91 98280 11002",
    salary: 25000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-AJ-103",
    staff_id: "HK-AJ-103",
    staffId: "HK-AJ-103",
    name: "Santosh Devi",
    username: "santosh.devi",
    password: "ajmer123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (03:00 PM - 11:30 PM)",
    assigned_area: "Lakefront Suites & Rooms",
    assignedArea: "Lakefront Suites & Rooms",
    assigned_work: "Lakefront Suites & Evening Turndown (Room 106)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "santosh.aj@hotel.com",
    phone: "+91 98280 11003",
    salary: 24500,
    joinedDate: "2025-03-15",
    joining_date: "2025-03-15",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-AJ-104",
    staff_id: "HK-AJ-104",
    staffId: "HK-AJ-104",
    name: "Manoj Chouhan",
    username: "manoj.chouhan",
    password: "ajmer123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Evening (03:00 PM - 11:30 PM)",
    assigned_area: "2nd Floor Guest Rooms",
    assignedArea: "2nd Floor Guest Rooms",
    assigned_work: "Guest Room Turnover & Restocking (Rooms 107, 108)",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "manoj.aj@hotel.com",
    phone: "+91 98280 11004",
    salary: 24000,
    joinedDate: "2025-04-10",
    joining_date: "2025-04-10",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "HK-AJ-105",
    staff_id: "HK-AJ-105",
    staffId: "HK-AJ-105",
    name: "Pushpa Solanki",
    username: "pushpa.solanki",
    password: "ajmer123",
    role: "housekeeping",
    department: "Housekeeping",
    shift: "Night (11:00 PM - 07:30 AM)",
    assigned_area: "Reception, Lobby & Lawns",
    assignedArea: "Reception, Lobby & Lawns",
    assigned_work: "Night Public Area Sanitization, Lobby & Guest Washrooms",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "pushpa.aj@hotel.com",
    phone: "+91 98280 11005",
    salary: 25500,
    joinedDate: "2025-05-01",
    joining_date: "2025-05-01",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
  },

  // KITCHEN (5 EMPLOYEES)
  {
    id: "KIT-AJ-101",
    staff_id: "KIT-AJ-101",
    staffId: "KIT-AJ-101",
    name: "Harish Chand",
    username: "harish.chand",
    password: "ajmer123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Main Dining Kitchen",
    assignedArea: "Main Dining Kitchen",
    assigned_work: "Executive Chef: Mughlai Curries, North Indian Thali & Breakfast Buffet",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "harish.chef@ajmer.com",
    phone: "+91 98280 22001",
    salary: 62000,
    joinedDate: "2025-01-15",
    joining_date: "2025-01-15",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-AJ-102",
    staff_id: "KIT-AJ-102",
    staffId: "KIT-AJ-102",
    name: "Kailash Mali",
    username: "kailash.mali",
    password: "ajmer123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Tandoor & Biryani Counter",
    assignedArea: "Tandoor & Biryani Counter",
    assigned_work: "Sous Chef: Dum Biryani, Kebabs & Tandoori Roti",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "kailash.cook@ajmer.com",
    phone: "+91 98280 22002",
    salary: 43000,
    joinedDate: "2025-02-20",
    joining_date: "2025-02-20",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-AJ-103",
    staff_id: "KIT-AJ-103",
    staffId: "KIT-AJ-103",
    name: "Shanti Vaishnav",
    username: "shanti.vaishnav",
    password: "ajmer123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (06:00 - 14:30)",
    assigned_area: "Sweets & Breakfast Prep",
    assignedArea: "Sweets & Breakfast Prep",
    assigned_work: "Halwai & Sweets: Ajmer Sohan Halwa, Kachori & Breakfast Line",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "shanti.kitchen@ajmer.com",
    phone: "+91 98280 22003",
    salary: 37000,
    joinedDate: "2025-03-01",
    joining_date: "2025-03-01",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-AJ-104",
    staff_id: "KIT-AJ-104",
    staffId: "KIT-AJ-104",
    name: "Narendra Verma",
    username: "narendra.verma",
    password: "ajmer123",
    role: "chef",
    department: "Kitchen",
    shift: "Evening (15:00 - 23:30)",
    assigned_area: "Banquet & Room Service",
    assignedArea: "Banquet & Room Service",
    assigned_work: "Room Service Fast Orders, Snacks & Banquet Curries",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "narendra.cook@ajmer.com",
    phone: "+91 98280 22004",
    salary: 35000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "KIT-AJ-105",
    staff_id: "KIT-AJ-105",
    staffId: "KIT-AJ-105",
    name: "Pappu Gurjar",
    username: "pappu.gurjar",
    password: "ajmer123",
    role: "chef",
    department: "Kitchen",
    shift: "Morning (07:00 - 15:30)",
    assigned_area: "Cold Pantry & Storage",
    assignedArea: "Cold Pantry & Storage",
    assigned_work: "Vegetable Prep, Salad Station & Dairy/Pantry Stock",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "pappu.pantry@ajmer.com",
    phone: "+91 98280 22005",
    salary: 32000,
    joinedDate: "2025-04-15",
    joining_date: "2025-04-15",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },

  // ACCOUNTING (5 EMPLOYEES)
  {
    id: "ACC-AJ-101",
    staff_id: "ACC-AJ-101",
    staffId: "ACC-AJ-101",
    name: "Vijay Sharma",
    username: "vijay.sharma",
    password: "ajmer123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Main Accounts Office",
    assignedArea: "Main Accounts Office",
    assigned_work: "Senior Accounts Officer: Ledger Balancing & Daily Financial Audit",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "vijay.acc@ajmer.com",
    phone: "+91 98280 33001",
    salary: 54000,
    joinedDate: "2025-01-20",
    joining_date: "2025-01-20",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-AJ-102",
    staff_id: "ACC-AJ-102",
    staffId: "ACC-AJ-102",
    name: "Anjali Mathur",
    username: "anjali.mathur",
    password: "ajmer123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Front Desk Cash Counter",
    assignedArea: "Front Desk Cash Counter",
    assigned_work: "Guest Room Billing, Advance Deposits & Folio Settling",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "anjali.bill@ajmer.com",
    phone: "+91 98280 33002",
    salary: 41000,
    joinedDate: "2025-02-15",
    joining_date: "2025-02-15",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-AJ-103",
    staff_id: "ACC-AJ-103",
    staffId: "ACC-AJ-103",
    name: "Pradeep Jain",
    username: "pradeep.jain",
    password: "ajmer123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Procurement & Vendor Desk",
    assignedArea: "Procurement & Vendor Desk",
    assigned_work: "Vendor Ledger, Grocery Purchase Invoices & Voucher Entry",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "pradeep.acc@ajmer.com",
    phone: "+91 98280 33003",
    salary: 43000,
    joinedDate: "2025-03-10",
    joining_date: "2025-03-10",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-AJ-104",
    staff_id: "ACC-AJ-104",
    staffId: "ACC-AJ-104",
    name: "Suman Choudhary",
    username: "suman.choudhary",
    password: "ajmer123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Payroll & HR Cell",
    assignedArea: "Payroll & HR Cell",
    assigned_work: "Staff Monthly Payroll, Overtime & Attendance Audits",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "suman.payroll@ajmer.com",
    phone: "+91 98280 33004",
    salary: 42000,
    joinedDate: "2025-03-25",
    joining_date: "2025-03-25",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "ACC-AJ-105",
    staff_id: "ACC-AJ-105",
    staffId: "ACC-AJ-105",
    name: "Deepak Kumawat",
    username: "deepak.kumawat",
    password: "ajmer123",
    role: "accountant",
    department: "Accounting",
    shift: "General (09:00 - 18:00)",
    assigned_area: "Bank & Tax Compliance",
    assignedArea: "Bank & Tax Compliance",
    assigned_work: "GST Returns, TDS Reconciliation & Bank Statement Matching",
    work_status: "On Duty",
    workStatus: "On Duty",
    email: "deepak.tax@ajmer.com",
    phone: "+91 98280 33005",
    salary: 46000,
    joinedDate: "2025-04-05",
    joining_date: "2025-04-05",
    status: "Active",
    orgId: "AJ01",
    org_id: "AJ01",
    org: "Ajmer Branch",
    org_name: "Ajmer Branch",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

export function getEmployees() {
  try {
    const key = getStorageKey();
    const raw = localStorage.getItem(key);
    const isAshirwad = key.includes("AS435") || key.includes("Ashirwad");
    const isCheery = key.includes("CH560") || key.includes("Cheery");
    const isJaipur = key.includes("JP01") || key.includes("Jaipur");
    const isAjmer = key.includes("AJ01") || key.includes("Ajmer");

    const defaultData = isJaipur
      ? JAIPUR_EMPLOYEES
      : isAjmer
      ? AJMER_EMPLOYEES
      : isAshirwad
      ? ASHIRWAD_EMPLOYEES
      : isCheery
      ? CHEERY_EMPLOYEES
      : INITIAL_DEFAULT_EMPLOYEES;

    if (raw) {
      let parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        // STRICT FILTER: Remove any legacy manager, front desk, or fake/unassigned accounts
        parsed = parsed.filter((e) => {
          if (!e) return false;
          const role = (e.role || "").toLowerCase();
          const dept = (e.department || "").toLowerCase();
          const id = String(e.id || e.staff_id || "");
          if (
            role === "manager" ||
            role === "front_desk" ||
            dept.includes("front") ||
            dept.includes("manage") ||
            id.startsWith("MGR-") ||
            id.startsWith("FD-") ||
            id.startsWith("EMP-ASH-01") ||
            id.startsWith("EMP-ASH-02") ||
            id.startsWith("STF-CH-201") ||
            id.startsWith("STF-CH-204")
          ) {
            return false;
          }
          return true;
        });

        // Canonical ID / Name map
        const byId = new Map();

        // 1. First add the 15 canonical staff members
        defaultData.forEach((defEmp) => {
          byId.set(defEmp.id, { ...defEmp });
        });

        // 2. Merge any user-added or updated fields
        parsed.forEach((emp) => {
          const empId = emp.id || emp.staff_id || emp.staffId;
          const normName = (emp.name || "").toLowerCase().trim();
          const matchingCanonical = byId.get(empId) || Array.from(byId.values()).find((c) => (c.name || "").toLowerCase().trim() === normName);

          if (matchingCanonical) {
            byId.set(matchingCanonical.id, {
              ...matchingCanonical,
              phone: emp.phone || matchingCanonical.phone,
              salary: emp.salary ?? matchingCanonical.salary,
              shift: emp.shift || matchingCanonical.shift,
              assigned_work: emp.assigned_work || matchingCanonical.assigned_work,
              assigned_area: emp.assigned_area || matchingCanonical.assigned_area,
              assignedArea: emp.assigned_area || matchingCanonical.assigned_area,
              work_status: emp.work_status || matchingCanonical.work_status,
              workStatus: emp.work_status || matchingCanonical.work_status,
              username: emp.username || matchingCanonical.username,
              password: emp.password || matchingCanonical.password,
              status: emp.status || matchingCanonical.status,
            });
          } else if (emp.isUserCreated && empId) {
            // Keep newly created staff if belonging to Housekeeping, Kitchen, or Accounting
            const d = (emp.department || "").toLowerCase();
            const r = (emp.role || "").toLowerCase();
            if (
              d.includes("housekeeping") ||
              d.includes("kitchen") ||
              d.includes("account") ||
              r.includes("housekeeping") ||
              r.includes("chef") ||
              r.includes("account")
            ) {
              byId.set(empId, emp);
            }
          }
        });

        const sanitized = Array.from(byId.values());
        localStorage.setItem(key, JSON.stringify(sanitized));
        return sanitized;
      }
    }
    localStorage.setItem(key, JSON.stringify(defaultData));
    return defaultData;
  } catch {
    return INITIAL_DEFAULT_EMPLOYEES;
  }
}

function save(list) {
  const key = getStorageKey();
  localStorage.setItem(key, JSON.stringify(list));
}

const BACKEND_URL = "http://localhost:4000";

export async function syncEmployeesFromBackend(orgId, orgName) {
  try {
    const params = new URLSearchParams();
    if (orgId) params.append("orgId", orgId);
    if (orgName) params.append("org", orgName);

    const headers = getAuthHeaders();

    // Fetch from dedicated /api/staff endpoint
    let res = await fetch(`${BACKEND_URL}/api/staff?${params.toString()}`, { headers });
    if (!res.ok) {
      res = await fetch(`${BACKEND_URL}/api/employees?${params.toString()}`, { headers });
    }

    if (res.ok) {
      const data = await res.json();
      const rawList = Array.isArray(data.staff) ? data.staff : (Array.isArray(data.employees) ? data.employees : []);
      if (rawList.length > 0) {
        const isAshirwad = (orgId && orgId.includes("AS435")) || (orgName && orgName.includes("Ashirwad"));
        const isCheery = (orgId && orgId.includes("CH560")) || (orgName && orgName.includes("Cheery"));
        const isJaipur = (orgId && orgId.includes("JP01")) || (orgName && orgName.includes("Jaipur"));
        const isAjmer = (orgId && orgId.includes("AJ01")) || (orgName && orgName.includes("Ajmer"));

        const defaultData = isJaipur
          ? JAIPUR_EMPLOYEES
          : isAjmer
          ? AJMER_EMPLOYEES
          : isAshirwad
          ? ASHIRWAD_EMPLOYEES
          : isCheery
          ? CHEERY_EMPLOYEES
          : INITIAL_DEFAULT_EMPLOYEES;

        // Filter out any unwanted Front Desk / Mgmt accounts
        const filteredList = rawList.filter((e) => {
          if (!e) return false;
          const role = (e.role || "").toLowerCase();
          const dept = (e.department || "").toLowerCase();
          const id = String(e.staff_id || e.staffId || e.id || "");
          if (
            role === "manager" ||
            role === "front_desk" ||
            dept.includes("front") ||
            dept.includes("manage") ||
            id.startsWith("MGR-") ||
            id.startsWith("FD-") ||
            id.startsWith("EMP-ASH-01") ||
            id.startsWith("EMP-ASH-02")
          ) {
            return false;
          }
          return true;
        });

        const mapped = filteredList.map((dbEmp) => {
          const sId = dbEmp.staff_id || dbEmp.staffId || dbEmp.id || `STF-${dbEmp.id}`;
          const match = defaultData.find((d) => d.id === sId || d.email === dbEmp.email);
          const dept = dbEmp.department || match?.department || "Housekeeping";
          const assignedWork = dbEmp.assigned_work || match?.assigned_work || (dept === "Housekeeping" ? "Room turnover & sanitization" : dept === "Kitchen" ? "Culinary prep & meal service" : "Ledger balancing & invoicing");

          return {
            id: sId,
            staff_id: sId,
            staffId: sId,
            name: dbEmp.name,
            username: dbEmp.username || match?.username || dbEmp.email?.split("@")[0] || "",
            password: dbEmp.password || match?.password || "ashirwad123",
            role: dbEmp.role || match?.role || "housekeeping",
            department: dept,
            shift: dbEmp.shift || match?.shift || "Morning (07:00 - 15:00)",
            status: dbEmp.status || "Active",
            assigned_area: dbEmp.assigned_area || dbEmp.assignedArea || match?.assigned_area || "Main Building",
            assignedArea: dbEmp.assigned_area || dbEmp.assignedArea || match?.assigned_area || "Main Building",
            assigned_work: assignedWork,
            work_status: dbEmp.work_status || dbEmp.workStatus || "On Duty",
            workStatus: dbEmp.work_status || dbEmp.workStatus || "On Duty",
            phone: dbEmp.phone || match?.phone || "",
            email: dbEmp.email || match?.email || "",
            salary: dbEmp.salary ?? match?.salary ?? 30000,
            joining_date: dbEmp.joining_date || dbEmp.joiningDate || match?.joinedDate || "2025-01-15",
            joiningDate: dbEmp.joining_date || dbEmp.joiningDate || match?.joinedDate || "2025-01-15",
            orgId: dbEmp.org_id || dbEmp.orgId || orgId,
            org: dbEmp.org_name || dbEmp.orgName || orgName,
            avatar: match?.avatar || "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
          };
        });

        // Ensure all 15 default staff are present
        const existingIds = new Set(mapped.map((e) => String(e.id || e.staff_id || e.staffId)));
        const existingEmails = new Set(mapped.map((e) => String(e.email || "").toLowerCase()));

        defaultData.forEach((defEmp) => {
          const id = String(defEmp.id);
          const email = String(defEmp.email).toLowerCase();
          if (!existingIds.has(id) && !existingEmails.has(email)) {
            mapped.push({ ...defEmp });
            existingIds.add(id);
            existingEmails.add(email);
          }
        });

        save(mapped);
        return mapped;
      }
    }
  } catch (err) {
    console.warn("Failed to fetch staff from backend DB:", err);
  }
  return getEmployees();
}

export async function addEmployee(emp) {
  try {
    const payload = {
      staff_id: emp.staff_id || emp.staffId || emp.id,
      staffId: emp.staff_id || emp.staffId || emp.id,
      name: emp.name,
      role: emp.role,
      department: emp.department || "Housekeeping",
      shift: emp.shift || "Morning (07:00 - 15:00)",
      status: emp.status || "Active",
      assigned_area: emp.assigned_area || emp.assignedArea || "1st Floor Rooms",
      assignedArea: emp.assigned_area || emp.assignedArea || "1st Floor Rooms",
      assigned_work: emp.assigned_work || (emp.department === "Housekeeping" ? "Room turnover & sanitization" : emp.department === "Kitchen" ? "Culinary prep & meal service" : emp.department === "Accounting" ? "Ledger balancing & invoicing" : "Room turnover & sanitization"),
      work_status: emp.work_status || emp.workStatus || "On Duty",
      workStatus: emp.work_status || emp.workStatus || "On Duty",
      phone: emp.phone || "",
      email: emp.email || "",
      password: emp.password || "matcha123",
      salary: emp.salary || null,
      joining_date: emp.joining_date || emp.joiningDate || null,
      joiningDate: emp.joining_date || emp.joiningDate || null,
      orgId: emp.orgId || emp.org_id || (emp.org === "Ashirwad" ? "AS435" : emp.org === "Cheery Clothing" ? "CH560" : "MA330"),
      orgName: emp.org || emp.orgName || emp.org_name || "Matcha Tea",
    };

    const headers = getAuthHeaders();

    const res = await fetch(`${BACKEND_URL}/api/staff`, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });

    if (res.ok) {
      const data = await res.json();
      const dbStaff = data.staff || data.employee || payload;
      const savedEmp = {
        ...emp,
        ...dbStaff,
        id: dbStaff.staff_id || dbStaff.staffId || emp.id,
        staffId: dbStaff.staff_id || dbStaff.staffId || emp.staffId || emp.id,
        isUserCreated: true,
      };
      const currentList = getEmployees();
      const index = currentList.findIndex((e) => e.id === savedEmp.id || (e.email && e.email === emp.email));
      if (index >= 0) {
        currentList[index] = savedEmp;
      } else {
        currentList.push(savedEmp);
      }
      save(currentList);
      return { success: true, employee: savedEmp };
    } else {
      const errorData = await res.json().catch(() => ({}));
      return { success: false, error: errorData.error || "Failed to add staff member to backend." };
    }
  } catch (err) {
    console.warn("Could not sync staff to backend DB, saving locally:", err);
  }

  const list = getEmployees();
  const fallbackEmp = { ...emp, isUserCreated: true };
  list.push(fallbackEmp);
  save(list);
  return { success: true, employee: fallbackEmp };
}

export function updateEmployee(id, patch) {
  const updatedList = getEmployees().map((e) => (e.id === id ? { ...e, ...patch } : e));
  save(updatedList);

  const updatedEmp = updatedList.find((e) => e.id === id);
  if (updatedEmp) {
    const payload = {
      id: updatedEmp.id,
      staff_id: updatedEmp.id || updatedEmp.staffId,
      staffId: updatedEmp.id || updatedEmp.staffId,
      name: updatedEmp.name,
      username: updatedEmp.username || (updatedEmp.email ? updatedEmp.email.split("@")[0] : String(updatedEmp.id).toLowerCase()),
      email: updatedEmp.email,
      password: updatedEmp.password || "password123",
      role: updatedEmp.role,
      department: updatedEmp.department || "Housekeeping",
      shift: updatedEmp.shift || "Morning (07:00 - 15:00)",
      status: updatedEmp.status || "Active",
      work_status: updatedEmp.work_status || updatedEmp.workStatus || "On Duty",
      workStatus: updatedEmp.work_status || updatedEmp.workStatus || "On Duty",
      assigned_area: updatedEmp.assigned_area || updatedEmp.assignedArea || "Main Building",
      assignedArea: updatedEmp.assigned_area || updatedEmp.assignedArea || "Main Building",
      assigned_work: updatedEmp.assigned_work || "",
      phone: updatedEmp.phone,
      salary: updatedEmp.salary,
      orgId: updatedEmp.orgId || "MA330",
      orgName: updatedEmp.org || updatedEmp.orgName || "Matcha Tea",
      org: updatedEmp.org || updatedEmp.orgName || "Matcha Tea",
    };

    fetch(`${BACKEND_URL}/api/staff`, {
      method: "POST",
      headers: { ...getAuthHeaders(), "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    }).catch(() => {
      fetch(`${BACKEND_URL}/api/employees`, {
        method: "POST",
        headers: { ...getAuthHeaders(), "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }).catch((err) => console.warn("Could not sync staff update to backend DB:", err));
    });
  }
}

export function deleteEmployee(id) {
  save(getEmployees().filter((e) => e.id !== id));

  fetch(`${BACKEND_URL}/api/employees/${id}`, {
    method: "DELETE",
    headers: getAuthHeaders(),
  }).catch((err) => console.warn("Could not sync staff deletion to backend DB:", err));
}

export function findEmployeeByEmailOrStaffId(input) {
  if (!input) return null;
  const key = input.trim().toLowerCase();

  const isMatch = (e) => {
    if (!e) return false;
    const emailMatch = e.email && e.email.toLowerCase() === key;
    const idMatch = e.id && e.id.toLowerCase() === key;
    const staffIdMatch = (e.staffId || e.staff_id) && String(e.staffId || e.staff_id).toLowerCase() === key;
    const usernameMatch = e.username && String(e.username).toLowerCase() === key;
    return Boolean(emailMatch || idMatch || staffIdMatch || usernameMatch);
  };

  // Helper to infer org details from storageKey if missing on employee object
  const inferOrg = (emp, storageKey) => {
    let org = emp.org;
    let orgId = emp.orgId;
    const k = (storageKey || "").toLowerCase();
    if (!org) {
      if (k.includes("jp01") || k.includes("jaipur")) org = "Jaipur Branch";
      else if (k.includes("aj01") || k.includes("ajmer")) org = "Ajmer Branch";
      else if (k.includes("as435") || k.includes("ashirwad")) org = "Ashirwad";
      else if (k.includes("ch560") || k.includes("cheery")) org = "Cheery Clothing";
      else if (k.includes("ma330") || k.includes("matcha")) org = "Matcha Tea";
    }
    if (!orgId) {
      if (k.includes("jp01") || k.includes("jaipur")) orgId = "JP01";
      else if (k.includes("aj01") || k.includes("ajmer")) orgId = "AJ01";
      else if (k.includes("as435") || k.includes("ashirwad")) orgId = "AS435";
      else if (k.includes("ch560") || k.includes("cheery")) orgId = "CH560";
      else if (k.includes("ma330") || k.includes("matcha")) orgId = "MA330";
    }
    return { ...emp, org, orgId };
  };

  // 1. Check in current org scoped storage
  try {
    const currentScoped = getEmployees();
    const foundInCurrent = currentScoped.find(isMatch);
    if (foundInCurrent) return inferOrg(foundInCurrent, getStorageKey());
  } catch (e) {}

  // 2. Search across ALL localStorage keys starting with "employees"
  for (let i = 0; i < localStorage.length; i++) {
    const storageKey = localStorage.key(i);
    if (storageKey && storageKey.startsWith("employees")) {
      try {
        const raw = localStorage.getItem(storageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          if (Array.isArray(parsed)) {
            const found = parsed.find(isMatch);
            if (found) return inferOrg(found, storageKey);
          }
        }
      } catch (err) {}
    }
  }

  // 3. Fallback across all canonical employees (all 5 branches: 75 total staff)
  const ALL_CANONICAL = [
    ...INITIAL_DEFAULT_EMPLOYEES,
    ...ASHIRWAD_EMPLOYEES,
    ...CHEERY_EMPLOYEES,
    ...JAIPUR_EMPLOYEES,
    ...AJMER_EMPLOYEES,
  ];
  const foundCanonical = ALL_CANONICAL.find(isMatch);
  if (foundCanonical) return foundCanonical;

  return null;
}

export function findEmployeeByEmail(email) {
  return findEmployeeByEmailOrStaffId(email);
}

// Auto-generated staff ID, e.g. MGR-482013 / FD-482013.
export function generateEmployeeId(role) {
  const prefix =
    role === "accountant" ? "ACC" :
    role === "housekeeping" ? "HK" :
    (role === "chef" || role === "kitchen") ? "KIT" : "STF";
  return `${prefix}-${Math.floor(100 + Math.random() * 900)}`;
}

