import "dotenv/config";
import { query } from "../db.js";

export const SEEDED_CUSTOMERS = [
  // CHEERY CLOTHING (CH560)
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-101",
    name: "Aarav Sharma",
    username: "@aaravsharma",
    gender: "Male",
    phone: "+91 98765 43210",
    email: "aarav.sharma@cheeryclothing.com",
    bookings: 8,
    tier: "Platinum",
    tier_color: "#7c3aed",
    tier_bg: "#f3e8ff",
    tier_icon: "👑",
    points: "1,240",
    stays: 8,
    last_visit: "18 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 105",
    check_in: "17 Aug 2026",
    check_out: "20 Aug 2026",
    stay_days: 3,
    guests_count: 2,
    total_bill: 12500,
    paid_amount: 12500,
    payment_status: "Paid",
    invoice_id: "INV-CH-2026-8891",
    document_name: "Aadhaar_Aarav.pdf",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-102",
    name: "Priya Patel",
    username: "@priyapatel",
    gender: "Female",
    phone: "+91 98234 56789",
    email: "priya.p@cheeryclothing.com",
    bookings: 4,
    tier: "Gold",
    tier_color: "#d97706",
    tier_bg: "#fef3c7",
    tier_icon: "⭐",
    points: "680",
    stays: 4,
    last_visit: "16 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 204",
    check_in: "16 Aug 2026",
    check_out: "18 Aug 2026",
    stay_days: 2,
    guests_count: 1,
    total_bill: 8400,
    paid_amount: 8400,
    payment_status: "Paid",
    invoice_id: "INV-CH-2026-7734",
    document_name: "Passport_Priya.pdf",
    document_type: "Passport",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-103",
    name: "Rohan Verma",
    username: "@rohanv",
    gender: "Male",
    phone: "+91 97112 34567",
    email: "rohan.v@cheeryclothing.com",
    bookings: 2,
    tier: "Silver",
    tier_color: "#475569",
    tier_bg: "#f1f5f9",
    tier_icon: "🥈",
    points: "310",
    stays: 2,
    last_visit: "12 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 301",
    check_in: "12 Aug 2026",
    check_out: "14 Aug 2026",
    stay_days: 2,
    guests_count: 2,
    total_bill: 9800,
    paid_amount: 0,
    payment_status: "Pending",
    invoice_id: "INV-CH-2026-5512",
    document_name: null,
    document_type: null,
    document_status: "Pending",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-104",
    name: "Ananya Roy",
    username: "@ananyaroy",
    gender: "Female",
    phone: "+91 96543 21098",
    email: "ananya.roy@cheeryclothing.com",
    bookings: 1,
    tier: "Daily Guest",
    tier_color: "#64748b",
    tier_bg: "#f1f5f9",
    tier_icon: "👤",
    points: "0",
    stays: 1,
    last_visit: "19 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 108",
    check_in: "19 Aug 2026",
    check_out: "22 Aug 2026",
    stay_days: 3,
    guests_count: 1,
    total_bill: 13050,
    paid_amount: 13050,
    payment_status: "Paid",
    invoice_id: "INV-CH-2026-9923",
    document_name: "Aadhaar_Ananya.jpg",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-105",
    name: "Vikramaditya Malhotra",
    username: "@vikramm",
    gender: "Male",
    phone: "+91 98111 22334",
    email: "vikram.m@cheeryclothing.com",
    bookings: 6,
    tier: "Platinum",
    tier_color: "#7c3aed",
    tier_bg: "#f3e8ff",
    tier_icon: "👑",
    points: "2,150",
    stays: 6,
    last_visit: "21 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 402",
    check_in: "20 Aug 2026",
    check_out: "24 Aug 2026",
    stay_days: 4,
    guests_count: 2,
    total_bill: 24000,
    paid_amount: 24000,
    payment_status: "Paid",
    invoice_id: "INV-CH-2026-1044",
    document_name: "Passport_Vikram.pdf",
    document_type: "Passport",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-106",
    name: "Sneha Kulkarni",
    username: "@snehak",
    gender: "Female",
    phone: "+91 97222 33445",
    email: "sneha.k@cheeryclothing.com",
    bookings: 3,
    tier: "Gold",
    tier_color: "#d97706",
    tier_bg: "#fef3c7",
    tier_icon: "⭐",
    points: "790",
    stays: 3,
    last_visit: "15 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 202",
    check_in: "15 Aug 2026",
    check_out: "17 Aug 2026",
    stay_days: 2,
    guests_count: 1,
    total_bill: 6500,
    paid_amount: 0,
    payment_status: "Pending",
    invoice_id: "INV-CH-2026-3022",
    document_name: null,
    document_type: null,
    document_status: "Pending",
  },

  // ASHIRWAD (AS435)
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-201",
    name: "Rajesh Sharma",
    username: "@rajeshsharma",
    gender: "Male",
    phone: "+91 98765 43210",
    email: "rajesh.sharma@ashirwad.com",
    bookings: 5,
    tier: "Platinum",
    tier_color: "#7c3aed",
    tier_bg: "#f3e8ff",
    tier_icon: "👑",
    points: "1,850",
    stays: 5,
    last_visit: "19 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 202",
    check_in: "18 Aug 2026",
    check_out: "21 Aug 2026",
    stay_days: 3,
    guests_count: 2,
    total_bill: 9000,
    paid_amount: 9000,
    payment_status: "Paid",
    invoice_id: "INV-AS-2026-4401",
    document_name: "Aadhaar_Rajesh.pdf",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-202",
    name: "Sunita Gupta",
    username: "@sunitag",
    gender: "Female",
    phone: "+91 97654 32109",
    email: "sunita.gupta@ashirwad.com",
    bookings: 4,
    tier: "Gold",
    tier_color: "#d97706",
    tier_bg: "#fef3c7",
    tier_icon: "⭐",
    points: "920",
    stays: 4,
    last_visit: "17 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 303",
    check_in: "16 Aug 2026",
    check_out: "19 Aug 2026",
    stay_days: 3,
    guests_count: 2,
    total_bill: 7800,
    paid_amount: 7800,
    payment_status: "Paid",
    invoice_id: "INV-AS-2026-5510",
    document_name: "VoterID_Sunita.jpg",
    document_type: "Voter ID",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-203",
    name: "Amitabh Verma",
    username: "@amitabhv",
    gender: "Male",
    phone: "+91 99887 76655",
    email: "amitabh.v@ashirwad.com",
    bookings: 2,
    tier: "Silver",
    tier_color: "#475569",
    tier_bg: "#f1f5f9",
    tier_icon: "🥈",
    points: "430",
    stays: 2,
    last_visit: "14 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 101",
    check_in: "14 Aug 2026",
    check_out: "15 Aug 2026",
    stay_days: 1,
    guests_count: 1,
    total_bill: 4400,
    paid_amount: 4400,
    payment_status: "Paid",
    invoice_id: "INV-AS-2026-2209",
    document_name: "Driving_Amitabh.pdf",
    document_type: "Driving License",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-204",
    name: "Vikramaditya Singh",
    username: "@vikramsingh",
    gender: "Male",
    phone: "+91 96543 21098",
    email: "vikram.singh@ashirwad.com",
    bookings: 9,
    tier: "Platinum",
    tier_color: "#7c3aed",
    tier_bg: "#f3e8ff",
    tier_icon: "👑",
    points: "3,400",
    stays: 9,
    last_visit: "22 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 404",
    check_in: "20 Aug 2026",
    check_out: "25 Aug 2026",
    stay_days: 5,
    guests_count: 3,
    total_bill: 30000,
    paid_amount: 15000,
    payment_status: "Pending",
    invoice_id: "INV-AS-2026-9900",
    document_name: "Passport_Vikramaditya.pdf",
    document_type: "Passport",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    customer_code: "C-205",
    name: "Meera Nair",
    username: "@meeranair",
    gender: "Female",
    phone: "+91 98333 44556",
    email: "meera.nair@ashirwad.com",
    bookings: 1,
    tier: "Daily Guest",
    tier_color: "#64748b",
    tier_bg: "#f1f5f9",
    tier_icon: "👤",
    points: "0",
    stays: 1,
    last_visit: "21 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 104",
    check_in: "21 Aug 2026",
    check_out: "24 Aug 2026",
    stay_days: 3,
    guests_count: 2,
    total_bill: 11200,
    paid_amount: 11200,
    payment_status: "Paid",
    invoice_id: "INV-AS-2026-3388",
    document_name: "Aadhaar_Meera.pdf",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },

  // MATCHA TEA (MA330)
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    customer_code: "C-301",
    name: "Tanvi Kapoor",
    username: "@tanvik",
    gender: "Female",
    phone: "+91 99111 22233",
    email: "tanvi.k@matchatea.com",
    bookings: 3,
    tier: "Gold",
    tier_color: "#d97706",
    tier_bg: "#fef3c7",
    tier_icon: "⭐",
    points: "850",
    stays: 3,
    last_visit: "18 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 102",
    check_in: "17 Aug 2026",
    check_out: "19 Aug 2026",
    stay_days: 2,
    guests_count: 1,
    total_bill: 5500,
    paid_amount: 5500,
    payment_status: "Paid",
    invoice_id: "INV-MA-2026-7011",
    document_name: "Aadhaar_Tanvi.pdf",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    customer_code: "C-302",
    name: "Siddharth Rao",
    username: "@siddharthr",
    gender: "Male",
    phone: "+91 98444 55667",
    email: "siddharth.r@matchatea.com",
    bookings: 7,
    tier: "Platinum",
    tier_color: "#7c3aed",
    tier_bg: "#f3e8ff",
    tier_icon: "👑",
    points: "2,600",
    stays: 7,
    last_visit: "20 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 201",
    check_in: "19 Aug 2026",
    check_out: "23 Aug 2026",
    stay_days: 4,
    guests_count: 2,
    total_bill: 14200,
    paid_amount: 14200,
    payment_status: "Paid",
    invoice_id: "INV-MA-2026-8800",
    document_name: "Passport_Siddharth.pdf",
    document_type: "Passport",
    document_status: "Uploaded & Verified",
  },
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    customer_code: "C-303",
    name: "Neha Bhatia",
    username: "@nehab",
    gender: "Female",
    phone: "+91 97555 66778",
    email: "neha.b@matchatea.com",
    bookings: 2,
    tier: "Silver",
    tier_color: "#475569",
    tier_bg: "#f1f5f9",
    tier_icon: "🥈",
    points: "410",
    stays: 2,
    last_visit: "16 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 304",
    check_in: "16 Aug 2026",
    check_out: "18 Aug 2026",
    stay_days: 2,
    guests_count: 2,
    total_bill: 8900,
    paid_amount: 0,
    payment_status: "Pending",
    invoice_id: "INV-MA-2026-3312",
    document_name: null,
    document_type: null,
    document_status: "Pending",
  },
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    customer_code: "C-304",
    name: "Karan Johar",
    username: "@karanjohar",
    gender: "Male",
    phone: "+91 98111 20001",
    email: "karan.j@matchatea.com",
    bookings: 1,
    tier: "Daily Guest",
    tier_color: "#64748b",
    tier_bg: "#f1f5f9",
    tier_icon: "👤",
    points: "0",
    stays: 1,
    last_visit: "22 Aug 2026",
    status: "Active",
    image: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=150&q=80",
    room_booked: "Room 106",
    check_in: "22 Aug 2026",
    check_out: "25 Aug 2026",
    stay_days: 3,
    guests_count: 1,
    total_bill: 16000,
    paid_amount: 16000,
    payment_status: "Paid",
    invoice_id: "INV-MA-2026-4099",
    document_name: "Aadhaar_Karan.jpg",
    document_type: "Aadhaar Card",
    document_status: "Uploaded & Verified",
  },
];

export async function initCustomersSchema() {
  try {
    console.log("🔄 Initializing Customers & Billing table & seeding records with org_id...");

    // Create table if not exists
    await query(`
      CREATE TABLE IF NOT EXISTS customers (
        id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
        org_id           VARCHAR(50) NOT NULL DEFAULT 'CH560',
        org_name         VARCHAR(255) DEFAULT 'Cheery Clothing',
        customer_code    VARCHAR(50) NOT NULL,
        name             VARCHAR(255) NOT NULL,
        username         VARCHAR(255) DEFAULT NULL,
        gender           VARCHAR(50) NOT NULL DEFAULT 'Male',
        phone            VARCHAR(100) NOT NULL,
        email            VARCHAR(255) NOT NULL,
        bookings         INT NOT NULL DEFAULT 1,
        tier             VARCHAR(100) NOT NULL DEFAULT 'Daily Guest',
        tier_color       VARCHAR(50) DEFAULT '#64748b',
        tier_bg          VARCHAR(50) DEFAULT '#f1f5f9',
        tier_icon        VARCHAR(50) DEFAULT '👤',
        points           VARCHAR(50) DEFAULT '0',
        stays            INT NOT NULL DEFAULT 1,
        last_visit       VARCHAR(100) DEFAULT NULL,
        status           VARCHAR(50) NOT NULL DEFAULT 'Active',
        image            TEXT DEFAULT NULL,
        room_booked      VARCHAR(100) NOT NULL DEFAULT 'Room 101',
        check_in         VARCHAR(100) DEFAULT NULL,
        check_out        VARCHAR(100) DEFAULT NULL,
        stay_days        INT NOT NULL DEFAULT 1,
        guests_count     INT NOT NULL DEFAULT 1,
        total_bill       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        paid_amount      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        payment_status   VARCHAR(50) NOT NULL DEFAULT 'Paid',
        invoice_id       VARCHAR(100) DEFAULT NULL,
        document_name    VARCHAR(255) DEFAULT NULL,
        document_type    VARCHAR(100) DEFAULT NULL,
        document_url     TEXT DEFAULT NULL,
        document_status  VARCHAR(100) NOT NULL DEFAULT 'Pending',
        created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_org_customer_code (org_id, customer_code)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    // Check if org_id column exists
    try {
      const colCheck = await query<any>("SHOW COLUMNS FROM customers LIKE 'org_id'");
      if (colCheck.length === 0) {
        await query("ALTER TABLE customers ADD COLUMN org_id VARCHAR(50) NOT NULL DEFAULT 'CH560'");
        await query("ALTER TABLE customers ADD COLUMN org_name VARCHAR(255) DEFAULT 'Cheery Clothing'");
        console.log("✅ Added org_id & org_name columns to customers table.");
      }
    } catch (e) {
      console.warn("Could not alter customers table for org_id:", e);
    }

    // Seed/Re-seed customer records
    const existing = await query<any>("SELECT COUNT(*) AS count FROM customers");
    const count = Number(existing[0]?.count || 0);

    if (count === 0 || count < 10) {
      for (const c of SEEDED_CUSTOMERS) {
        await query(
          `INSERT INTO customers 
          (org_id, org_name, customer_code, name, username, gender, phone, email, bookings, tier, tier_color, tier_bg, tier_icon, points, stays, last_visit, status, image, room_booked, check_in, check_out, stay_days, guests_count, total_bill, paid_amount, payment_status, invoice_id, document_name, document_type, document_status)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
          ON DUPLICATE KEY UPDATE 
            name = VALUES(name),
            org_name = VALUES(org_name),
            email = VALUES(email),
            phone = VALUES(phone),
            total_bill = VALUES(total_bill),
            paid_amount = VALUES(paid_amount),
            payment_status = VALUES(payment_status)`,
          [
            c.org_id,
            c.org_name,
            c.customer_code,
            c.name,
            c.username,
            c.gender,
            c.phone,
            c.email,
            c.bookings,
            c.tier,
            c.tier_color,
            c.tier_bg,
            c.tier_icon,
            c.points,
            c.stays,
            c.last_visit,
            c.status,
            c.image,
            c.room_booked,
            c.check_in,
            c.check_out,
            c.stay_days,
            c.guests_count,
            c.total_bill,
            c.paid_amount,
            c.payment_status,
            c.invoice_id,
            c.document_name,
            c.document_type,
            c.document_status,
          ]
        );
      }
      console.log(`✅ Seeded ${SEEDED_CUSTOMERS.length} customer & billing records with org_id into database.`);
    }
  } catch (error: any) {
    console.warn("⚠️ Warning during initCustomersSchema:", error.message);
  }
}
