import "dotenv/config";
import { query } from "../db.js";

export const SEEDED_HK_TASKS = [
  // CHEERY CLOTHING (CH560)
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    task_code: "HK-CH-101",
    room: "Room 101",
    floor: "1st Floor • Executive King Suite",
    room_type: "Executive King Suite",
    staff: "Sunita Devi",
    staff_email: "sunita.housekeeping@cheeryclothing.com",
    staff_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80",
    status: "Cleaned & Approved",
    status_color: "#16a34a",
    status_bg: "#dcfce7",
    priority: "VIP Reserved",
    priority_color: "#7c3aed",
    priority_bg: "#f3e8ff",
    task: "Deep Sanitize & Linen Change",
    last_cleaned: "Today, 10:15 AM",
    progress: 100,
    icon: "🧼",
    assigned_time: "09:00 AM",
    notes: "Executive King suite fully disinfected & linen replaced.",
    photo_proof_url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
    photo_uploaded_at: "Today, 10:00 AM",
    approval_status: "Approved by Admin (super_admin)",
    approved_by: "Admin (super_admin)",
    rejected_reason: null,
    status_action_at: "Today, 10:15 AM",
    status_action_by: "Admin (super_admin)",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    task_code: "HK-CH-202",
    room: "Room 202",
    floor: "2nd Floor • Deluxe Ocean View",
    room_type: "Deluxe Ocean View",
    staff: "Ramesh Kumar",
    staff_email: "ramesh.housekeeping@cheeryclothing.com",
    staff_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    status: "Cleaning",
    status_color: "#d97706",
    status_bg: "#fef3c7",
    priority: "Urgent Checkout",
    priority_color: "#dc2626",
    priority_bg: "#fee2e2",
    task: "Daily Turn-down & Washroom Sanitization",
    last_cleaned: "In Progress",
    progress: 45,
    icon: "🧹",
    assigned_time: "11:00 AM",
    notes: "Guest checkout completed at 10:45 AM. Cleaning in progress.",
    photo_proof_url: null,
    photo_uploaded_at: null,
    approval_status: "Pending Cleaning",
    approved_by: null,
    rejected_reason: null,
    status_action_at: null,
    status_action_by: null,
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    task_code: "HK-CH-301",
    room: "Room 301",
    floor: "3rd Floor • Suite Room",
    room_type: "Suite Room",
    staff: "Anil Gupta",
    staff_email: "anil.housekeeping@cheeryclothing.com",
    staff_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    status: "Photo Uploaded",
    status_color: "#7c3aed",
    status_bg: "#ede9fe",
    priority: "Normal",
    priority_color: "#475569",
    priority_bg: "#f1f5f9",
    task: "Full Linen Change & Vacuuming",
    last_cleaned: "Photo Submitted",
    progress: 90,
    icon: "📸",
    assigned_time: "10:30 AM",
    notes: "Linen changed & photo proof submitted for manager review.",
    photo_proof_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    photo_uploaded_at: "Today, 11:40 AM",
    approval_status: "Pending Approval",
    approved_by: null,
    rejected_reason: null,
    status_action_at: "Today, 11:40 AM",
    status_action_by: "Anil Gupta (Staff)",
  },
  {
    org_id: "CH560",
    org_name: "Cheery Clothing",
    task_code: "HK-CH-404",
    room: "Room 404",
    floor: "4th Floor • Deluxe King",
    room_type: "Deluxe King",
    staff: "Sunita Devi",
    staff_email: "sunita.housekeeping@cheeryclothing.com",
    staff_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80",
    status: "Rescheduled",
    status_color: "#d97706",
    status_bg: "#fef3c7",
    priority: "Normal",
    priority_color: "#475569",
    priority_bg: "#f1f5f9",
    task: "Sanitization & Refill Amenities",
    last_cleaned: "Re-cleaning Required",
    progress: 25,
    icon: "🔄",
    assigned_time: "08:30 AM",
    notes: "Bathroom mirror needs re-polishing. Scheduled for 02:00 PM.",
    photo_proof_url: null,
    photo_uploaded_at: null,
    approval_status: "Rejected - Re-cleaning Scheduled",
    approved_by: null,
    rejected_reason: "Bathroom mirror spot remaining.",
    status_action_at: "Today, 11:00 AM",
    status_action_by: "Admin (super_admin)",
  },

  // ASHIRWAD (AS435)
  {
    org_id: "AS435",
    org_name: "Ashirwad",
    task_code: "HK-ASH-101",
    room: "Room 101",
    floor: "1st Floor • Royal Suite",
    room_type: "Royal Suite",
    staff: "Rajesh Sharma",
    staff_email: "rajesh.housekeeping@ashirwad.com",
    staff_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80",
    status: "Cleaned & Approved",
    status_color: "#16a34a",
    status_bg: "#dcfce7",
    priority: "VIP Reserved",
    priority_color: "#7c3aed",
    priority_bg: "#f3e8ff",
    task: "Royal Suite Deep Sanitize & Rose Water Diffuser",
    last_cleaned: "Today, 09:45 AM",
    progress: 100,
    icon: "🧼",
    assigned_time: "08:30 AM",
    notes: "VIP Royal Suite fully disinfected with fresh Rose diffuser.",
    photo_proof_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    photo_uploaded_at: "Today, 09:30 AM",
    approval_status: "Approved by Rajesh Verma (Manager)",
    approved_by: "Rajesh Verma (Manager)",
    rejected_reason: null,
    status_action_at: "Today, 09:45 AM",
    status_action_by: "Rajesh Verma (Manager)",
  },
  {
    org_id: "AS435",
    org_name: "Ashirwad",
    task_code: "HK-ASH-202",
    room: "Room 202",
    floor: "2nd Floor • Grand Deluxe Room",
    room_type: "Grand Deluxe Room",
    staff: "Priya Patel",
    staff_email: "priya.housekeeping@ashirwad.com",
    staff_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80",
    status: "Cleaning",
    status_color: "#d97706",
    status_bg: "#fef3c7",
    priority: "Urgent Checkout",
    priority_color: "#dc2626",
    priority_bg: "#fee2e2",
    task: "Complete Bathroom Sanitization & Linen Refresh",
    last_cleaned: "In Progress",
    progress: 60,
    icon: "🧹",
    assigned_time: "10:15 AM",
    notes: "Guest checkout completed at 10:00 AM.",
    photo_proof_url: null,
    photo_uploaded_at: null,
    approval_status: "Pending Cleaning",
    approved_by: null,
    rejected_reason: null,
    status_action_at: null,
    status_action_by: null,
  },
  {
    org_id: "AS435",
    org_name: "Ashirwad",
    task_code: "HK-ASH-303",
    room: "Room 303",
    floor: "3rd Floor • Executive Room",
    room_type: "Executive Room",
    staff: "Amitabh Verma",
    staff_email: "amitabh.housekeeping@ashirwad.com",
    staff_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    status: "Photo Uploaded",
    status_color: "#7c3aed",
    status_bg: "#ede9fe",
    priority: "Normal",
    priority_color: "#475569",
    priority_bg: "#f1f5f9",
    task: "Towel & Amenities Restock",
    last_cleaned: "Photo Submitted",
    progress: 90,
    icon: "📸",
    assigned_time: "11:00 AM",
    notes: "Fresh towels & toiletries restocked.",
    photo_proof_url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
    photo_uploaded_at: "Today, 11:55 AM",
    approval_status: "Pending Approval",
    approved_by: null,
    rejected_reason: null,
    status_action_at: "Today, 11:55 AM",
    status_action_by: "Amitabh Verma (Staff)",
  },

  // MATCHA TEA (MA330)
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    task_code: "HK-MA-101",
    room: "Room 101",
    floor: "1st Floor • Zen Tea Suite",
    room_type: "Zen Tea Suite",
    staff: "Meera Nair",
    staff_email: "meera.housekeeping@matchatea.com",
    staff_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80",
    status: "Cleaned & Approved",
    status_color: "#16a34a",
    status_bg: "#dcfce7",
    priority: "VIP Reserved",
    priority_color: "#7c3aed",
    priority_bg: "#f3e8ff",
    task: "Bamboo Towel Restock & Tea Set Clean",
    last_cleaned: "Today, 08:50 AM",
    progress: 100,
    icon: "🍵",
    assigned_time: "08:00 AM",
    notes: "Ceremonial tea set sanitized & bamboo towels placed.",
    photo_proof_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    photo_uploaded_at: "Today, 08:40 AM",
    approval_status: "Approved by Admin",
    approved_by: "Admin",
    rejected_reason: null,
    status_action_at: "Today, 08:50 AM",
    status_action_by: "Admin",
  },
  {
    org_id: "MA330",
    org_name: "Matcha Tea",
    task_code: "HK-MA-202",
    room: "Room 202",
    floor: "2nd Floor • Japanese Style Deluxe",
    room_type: "Japanese Style Deluxe",
    staff: "Vikramaditya Singh",
    staff_email: "vikram.housekeeping@matchatea.com",
    staff_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    status: "Cleaning",
    status_color: "#d97706",
    status_bg: "#fef3c7",
    priority: "Normal",
    priority_color: "#475569",
    priority_bg: "#f1f5f9",
    task: "Linen Change & Tatami Mat Sanitize",
    last_cleaned: "In Progress",
    progress: 50,
    icon: "🧹",
    assigned_time: "10:00 AM",
    notes: "Tatami mats vacuumed & sanitized.",
    photo_proof_url: null,
    photo_uploaded_at: null,
    approval_status: "Pending Cleaning",
    approved_by: null,
    rejected_reason: null,
    status_action_at: null,
    status_action_by: null,
  },
];

export async function initHousekeepingSchema() {
  try {
    console.log("🔄 Initializing Housekeeping Tasks table & seeding default tasks...");

    // Create table if not exists
    await query(`
      CREATE TABLE IF NOT EXISTS housekeeping_tasks (
        id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
        org_id            VARCHAR(50) NOT NULL DEFAULT 'CH560',
        org_name          VARCHAR(255) DEFAULT 'Cheery Clothing',
        task_code         VARCHAR(100) NOT NULL,
        room              VARCHAR(100) NOT NULL,
        floor             VARCHAR(255) DEFAULT NULL,
        room_type         VARCHAR(100) DEFAULT NULL,
        staff             VARCHAR(255) NOT NULL DEFAULT 'Sunita Devi',
        staff_email       VARCHAR(255) DEFAULT NULL,
        staff_avatar      TEXT DEFAULT NULL,
        status            VARCHAR(100) NOT NULL DEFAULT 'Cleaning',
        status_color      VARCHAR(50) DEFAULT '#d97706',
        status_bg         VARCHAR(50) DEFAULT '#fef3c7',
        priority          VARCHAR(100) NOT NULL DEFAULT 'Normal',
        priority_color    VARCHAR(50) DEFAULT '#475569',
        priority_bg       VARCHAR(50) DEFAULT '#f1f5f9',
        task              VARCHAR(255) NOT NULL,
        last_cleaned      VARCHAR(100) DEFAULT NULL,
        progress          INT NOT NULL DEFAULT 10,
        icon              VARCHAR(50) DEFAULT '🧼',
        assigned_time     VARCHAR(100) DEFAULT NULL,
        notes             TEXT DEFAULT NULL,
        photo_proof_url   TEXT DEFAULT NULL,
        photo_uploaded_at VARCHAR(100) DEFAULT NULL,
        approval_status   VARCHAR(255) DEFAULT 'Pending',
        approved_by       VARCHAR(255) DEFAULT NULL,
        rejected_reason   TEXT DEFAULT NULL,
        status_action_at  VARCHAR(100) DEFAULT NULL,
        status_action_by  VARCHAR(255) DEFAULT NULL,
        created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE KEY uq_org_task_code (org_id, task_code)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    // Drop video columns if they exist
    try {
      const vidColCheck = await query<any>("SHOW COLUMNS FROM housekeeping_tasks LIKE 'video_proof_url'");
      if (vidColCheck.length > 0) {
        await query("ALTER TABLE housekeeping_tasks DROP COLUMN video_proof_url");
        console.log("🗑️ Dropped video_proof_url column from housekeeping_tasks table.");
      }
      const vidDateColCheck = await query<any>("SHOW COLUMNS FROM housekeeping_tasks LIKE 'video_uploaded_at'");
      if (vidDateColCheck.length > 0) {
        await query("ALTER TABLE housekeeping_tasks DROP COLUMN video_uploaded_at");
        console.log("🗑️ Dropped video_uploaded_at column from housekeeping_tasks table.");
      }
    } catch (e) {
      console.warn("Could not drop video columns from housekeeping_tasks:", e);
    }

    // Check if org_id column exists
    try {
      const colCheck = await query<any>("SHOW COLUMNS FROM housekeeping_tasks LIKE 'org_id'");
      if (colCheck.length === 0) {
        await query("ALTER TABLE housekeeping_tasks ADD COLUMN org_id VARCHAR(50) NOT NULL DEFAULT 'CH560'");
        await query("ALTER TABLE housekeeping_tasks ADD COLUMN org_name VARCHAR(255) DEFAULT 'Cheery Clothing'");
        console.log("✅ Added org_id & org_name columns to housekeeping_tasks table.");
      }
    } catch (e) {
      console.warn("Could not alter housekeeping_tasks table for org_id:", e);
    }

    // Seed/Re-seed tasks into database for each organization
    for (const t of SEEDED_HK_TASKS) {
      await query(
        `INSERT INTO housekeeping_tasks 
        (org_id, org_name, task_code, room, floor, room_type, staff, staff_email, staff_avatar, status, status_color, status_bg, priority, priority_color, priority_bg, task, last_cleaned, progress, icon, assigned_time, notes, photo_proof_url, photo_uploaded_at, approval_status, approved_by, rejected_reason, status_action_at, status_action_by)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE
          room = VALUES(room),
          floor = VALUES(floor),
          room_type = VALUES(room_type),
          staff = VALUES(staff),
          staff_email = VALUES(staff_email),
          staff_avatar = VALUES(staff_avatar),
          status = VALUES(status),
          status_color = VALUES(status_color),
          status_bg = VALUES(status_bg),
          priority = VALUES(priority),
          priority_color = VALUES(priority_color),
          priority_bg = VALUES(priority_bg),
          task = VALUES(task),
          last_cleaned = VALUES(last_cleaned),
          progress = VALUES(progress),
          icon = VALUES(icon),
          assigned_time = VALUES(assigned_time),
          notes = VALUES(notes),
          photo_proof_url = VALUES(photo_proof_url),
          photo_uploaded_at = VALUES(photo_uploaded_at),
          approval_status = VALUES(approval_status),
          approved_by = VALUES(approved_by),
          rejected_reason = VALUES(rejected_reason),
          status_action_at = VALUES(status_action_at),
          status_action_by = VALUES(status_action_by)`,
        [
          t.org_id,
          t.org_name,
          t.task_code,
          t.room,
          t.floor,
          t.room_type,
          t.staff,
          t.staff_email,
          t.staff_avatar,
          t.status,
          t.status_color,
          t.status_bg,
          t.priority,
          t.priority_color,
          t.priority_bg,
          t.task,
          t.last_cleaned,
          t.progress,
          t.icon,
          t.assigned_time,
          t.notes,
          t.photo_proof_url,
          t.photo_uploaded_at,
          t.approval_status,
          t.approved_by,
          t.rejected_reason,
          t.status_action_at,
          t.status_action_by,
        ]
      );
    }

    console.log("✅ Seeded housekeeping tasks into MySQL database successfully.");
  } catch (error: any) {
    console.warn("⚠️ Warning during initHousekeepingSchema:", error.message);
  }
}

if (process.argv[1] && process.argv[1].includes("init-housekeeping-schema")) {
  initHousekeepingSchema().then(() => process.exit(0));
}
